version: "2"

go: "1.25"

run:
  timeout: 5m
  skip-files:
    - types_gen\.go
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  format: colored-line-number
